<?php
Kirby::plugin('fz/nova-blocks', [
  'blueprints' => [
      //fields
      'fields/advanced-fields' => __DIR__ . '/blueprints/fields/advanced-fields.yml',
      'fields/align-block' => __DIR__ . '/blueprints/fields/align-block.yml',
      'fields/align-content' => __DIR__ . '/blueprints/fields/align-content.yml',
      'fields/background' => __DIR__ . '/blueprints/fields/background.yml',
      'fields/block-background' => __DIR__ . '/blueprints/fields/block-background.yml',
      'fields/blocks' => __DIR__ . '/blueprints/fields/blocks.yml',
      'fields/blocksettings' => __DIR__ . '/blueprints/fields/blocksettings.yml',
      'fields/color-options' => __DIR__ . '/blueprints/fields/color-options.yml',
      'fields/font-color' => __DIR__ . '/blueprints/fields/font-color.yml',
      'fields/form-fields' => __DIR__ . '/blueprints/fields/form-fields.yml',
      'fields/form-settings' => __DIR__ . '/blueprints/fields/form-settings.yml',
      'fields/layout' => __DIR__ . '/blueprints/fields/layout.yml',
      'fields/layout-settings' => __DIR__ . '/blueprints/fields/layout-settings.yml',
      'fields/linkfield' => __DIR__ . '/blueprints/fields/linkfield.yml',
      'fields/width' => __DIR__ . '/blueprints/fields/width.yml',
      //blocks
      'blocks/accordion' => __DIR__ . '/blueprints/blocks/accordion.yml',
      'blocks/accordionitem' => __DIR__ . '/blueprints/blocks/accordionitem.yml',
      'blocks/blurb' => __DIR__ . '/blueprints/blocks/blurb.yml',
      'blocks/button' => __DIR__ . '/blueprints/blocks/button.yml',
      'blocks/carousel' => __DIR__ . '/blueprints/blocks/carousel.yml',
      'blocks/cookiesettings' => __DIR__ . '/blueprints/blocks/cookiesettings.yml',
      'blocks/form' => __DIR__ . '/blueprints/blocks/form.yml',
      'blocks/gallery' => __DIR__ . '/blueprints/blocks/gallery.yml',
      'blocks/hero' => __DIR__ . '/blueprints/blocks/hero.yml',
      'blocks/icon' => __DIR__ . '/blueprints/blocks/icon.yml',
      'blocks/iframe' => __DIR__ . '/blueprints/blocks/iframe.yml',
      'blocks/image' => __DIR__ . '/blueprints/blocks/image.yml',
      'blocks/info' => __DIR__ . '/blueprints/blocks/info.yml',
      'blocks/markdown' => __DIR__ . '/blueprints/blocks/markdown.yml',
      'blocks/openingtimes' => __DIR__ . '/blueprints/blocks/openingtimes.yml',
      'blocks/pricing' => __DIR__ . '/blueprints/blocks/pricing.yml',
      'blocks/quote' => __DIR__ . '/blueprints/blocks/quote.yml',
      'blocks/spacer' => __DIR__ . '/blueprints/blocks/spacer.yml',
      'blocks/table' => __DIR__ . '/blueprints/blocks/table.yml',
      'blocks/teaser' => __DIR__ . '/blueprints/blocks/teaser.yml',
      'blocks/testimonial' => __DIR__ . '/blueprints/blocks/testimonial.yml',
      'blocks/text' => __DIR__ . '/blueprints/blocks/text.yml',
      'blocks/video' => __DIR__ . '/blueprints/blocks/video.yml',
      'blocks/videoembed' => __DIR__ . '/blueprints/blocks/videoembed.yml',
  ],
  'snippets' => [
      'blocks/accordion' => __DIR__ . '/snippets/accordion.php',
      'blocks/accordionitem' => __DIR__ . '/snippets/accordionitem.php',
      'blocks/blurb' => __DIR__ . '/snippets/blurb.php',
      'blocks/button' => __DIR__ . '/snippets/button.php',
      'blocks/carousel' => __DIR__ . '/snippets/carousel.php',
      'blocks/cookiesettings' => __DIR__ . '/snippets/cookiesettings.php',
      'blocks/form' => __DIR__ . '/snippets/form.php',
      'blocks/gallery' => __DIR__ . '/snippets/gallery.php',
      'blocks/hero' => __DIR__ . '/snippets/hero.php',
      'blocks/icon' => __DIR__ . '/snippets/icon.php',
      'blocks/iframe' => __DIR__ . '/snippets/iframe.php',
      'blocks/image' => __DIR__ . '/snippets/image.php',
      'blocks/info' => __DIR__ . '/snippets/info.php',
      'blocks/markdown' => __DIR__ . '/snippets/markdown.php',
      'blocks/openingtimes' => __DIR__ . '/snippets/openingtimes.php',
      'blocks/pricing' => __DIR__ . '/snippets/pricing.php',
      'blocks/quote' => __DIR__ . '/snippets/quote.php',
      'blocks/spacer' => __DIR__ . '/snippets/spacer.php',
      'blocks/table' => __DIR__ . '/snippets/table.php',
      'blocks/teaser' => __DIR__ . '/snippets/teaser.php',
      'blocks/testimonial' => __DIR__ . '/snippets/testimonial.php',
      'blocks/text' => __DIR__ . '/snippets/text.php',
      'blocks/video' => __DIR__ . '/snippets/video.php',
      'blocks/videoembed' => __DIR__ . '/snippets/videoembed.php'
  ],
  'translations' => [
    'en' => [
        'no-image-selected' => 'Select Image(s)...',
        'select-video' => 'Select Video...',
        'select-page' => 'Select Page...',
        'spacer' => 'Vertical Space',
        'carousel' => 'Carousel',
        'empty' => 'Empty...',
        'pricing' => 'Add pricing...',
        'table' => 'Table',
        'form' => 'Contact Form',
    ],
    'de' => [
        'no-image-selected' => 'Bild(er) auswählen...',
        'select-video' => 'Video auswählen...',
        'select-page' => 'Seite wählen...',
        'spacer' => 'Vertikaler Abstand',
        'carousel' => 'Karussell',
        'empty' => 'Leer...',
        'pricing' => 'Preis hinzufügen...',
        'table' => 'Tabelle',
        'form' => 'Kontaktformular',
    ]
  ]
]);