version: '3'
services:
    web:
        build: 
          context: .
          dockerfile: ./docker/nginx.Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/fastcgi.conf:/etc/nginx/fastcgi.conf
            - ./:/app

    php:
        build:
            context: .
            dockerfile: ./docker/php.Dockerfile
        volumes:
            - ./:/app