title: 
  en: Page
  de: Seite
image:
  back: gray-800
  icon: page

options:
  changeSlug:
    admin: true
    author: false
    editor: true
  changeStatus:
    admin: true
    author: false
    editor: true
  changeTitle:
    admin: true
    author: false
    editor: true
  create:
    admin: true
    author: false
    editor: true
  delete:
    admin: true
    author: false
    editor: true
  duplicate:
    admin: true
    author: false
    editor: true
  update:
    admin: true
    author: false
    editor: true

status:
  extends: sections/status

tabs:
  content:
    label:
      en: Content
      de: Inhalt
    icon: text
    fields:
      blocks: fields/layout

  filestab:
    label:
        en: files
        de: Dateien
    icon: image
    sections:
      files:
        headline: 
          en: Files
          de: Dateien
        sortBy: date desc
        type: files
        layout: cards
        info: "{{ file.alt }}"

  subpages:
    label:
      en: Subpages
      de: Unterseiten
    icon: page
    columns:
      - width: 1/3
        sections:
          drafts:
            headline: 
              en: Drafts
              de: Entwürfe
            image: page.cover.toFile
            status: draft
            template:
              - default
              - posts
            type: pages

      - width: 2/3
        sections:
          listed:
            headline: 
              en: Listed
              de: Gelistet
            image:
              cover: true
              query: page.cover.toFile
              ratio: 2/1
            layout: cardlets
            info: "Template: {{ page.template }}"
            status: listed
            type: pages
          unlisted:
            headline: 
              en: Unlisted
              de: Ungelistet
            image: page.cover.toFile
            status: unlisted
            type: pages
            layout: cardlets
            info: "Template: {{ page.template }}"
            help:
              en: these pages are published and can be reached with their url.
              de: Diese Seiten sind veröffentlicht und über ihre URL erreichbar.

  advanced:
    extends: fields/advanced-fields